name: CI/CD Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 3️⃣ Build da imagem Docker e push para o Docker Hub
      - name: Build and Push Docker Image
        run: |
          docker build -t anavimiza/angular-ecommerce-app:prod .
          docker push anavimiza/angular-ecommerce-app:prod

      # 4️⃣ Conexão SSH com EC2 e deploy via docker-compose
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/angular-ecommerce-app

            # Puxa as últimas mudanças do repositório
            git pull

            # Atualiza imagem do Docker Hub
            docker pull anavimiza/angular-ecommerce-app:prod

            # Derruba containers antigos e sobe de novo
            docker-compose down
            docker-compose up -d

            echo "✅ Deploy concluído com sucesso!"
